def my_function(arg1, arg2, arg3)

def my_function(*arguments)

def my_function(*numbers, number1) -> error